# -*- coding: utf-8 -*-
"""Multiple Linear Regression

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1679DbKoT6kBOVZLlve5dBDHJuKBmtGXQ

# **ÇOKLU DOĞRUSAL REGRESYON**
"""

# Temel amaç, bağımlı ve bağımsız değişkenler arasındaki ilişkiyi ifade eden doğrusal fonksiyonu bulmaktır.

# Hatalar normal dağılır.
# Hatalar birbirinden bağımsızdır ve aralarında otokorelasyon yoktur.
# Her bir gözlem için hata terimler varyansları sabittir.
# Değişkenler ile hata terimi arasında ilişki yoktur.
# Bağımsız değişkenler arasında çoklu doğrusal ilişki problemi yoktur.

"""**Avantajları ve Dezavantajları**
- Doğrusallık nesnellik yorumları yapılabilmesini sağlar, bu durum aksiyoner ve stratejik modelleme imkanı verir.
- Değişkenlerin etki düzeyleriyle anlamlılıkları değerlendirilebilir.
- Bağımlı değişkendeki değişkenliğin açıklanma başarısı ölçülebilir.
- Model anlamlılığı değerlendirilebilir.
- Varsayımları vardır.
- Aykırı gözlemler duyarlıdır.
"""

import pandas as pd
df = pd.read_csv("/Advertising.csv")
df = df.iloc[:,1:len(df)]
df.head()

X = df.drop('sales', axis=1)
y = df[["sales"]] #pandas dataframe yapmak için 2 parantez

y.head()

X.head()



"""#### Statsmodels ile model kurma"""

import statsmodels.api as sm

lm = sm.OLS(y,X)
#(bağımlı değişkeni, bağımsız değişkeni)

model = lm.fit()

model.summary() #Çoklu doğrusal regresyonun model çıktısıdır.

"""- **R square**: Bağımsız değişkendeki bağımlı değişkenleri açıklama yüzdesidir.
> 0.98 demekki satışlardaki değişimi açıklamak için çok iyi 3 tane değişkenimiz var demektir. 

- **Adj. R-squared (uncentered)**: R kare değerinin düzeltilmiş halidir. R kare değerine ne kadar değişken eklenirse eklensin şişmeye meyillidir. Bu durum modelde ilgili ya da ilgisiz değişken bulundurma eğilimine sebep olmaktadır. 

- **F-stat**: Modelin anlamlılığını test etmek için kullanılan istatistiktir. 0.05'den küçük bir değer olduğu için modelin anlamlı olduğu bilgisini verir.

- **Prob (F-statistic)**: F istatisliğine ilişkin p value değeridir. 
> 0.05'den küçük bir değer olduğu için modelin anlamlı olduğu bilgisini verir.

- **T-stat**: Elimizide bir katsayı var ama bu katsayı anlamlı mı ?
> p-value değerlerine bakıldığında modellemek için kullanılan tüm değerler anlamlıdır. 
> 0.05'den küçük p-value değerleri olduğu için reddedilir. Bu modellemede kullanılan değişkenlerin anlamlı olduğu anlamına gelir.


"""

#scikit learn ile model kurmak

from sklearn.linear_model import LinearRegression
lm = LinearRegression()

model = lm.fit(X,y)

model.intercept_ #sabit

model.coef_

"""### **Tahmin**"""

# 30 br Tv, 10 br radio, 40 br gazete

yeni_veri = [[30],[10],[40]]

import pandas as pd
yeni_veri = pd.DataFrame(yeni_veri).T

yeni_veri #bağısmız değişkenlerin değerleri

model.predict(yeni_veri) #tahmin edilen değer

from sklearn.metrics import mean_squared_error

MSE = mean_squared_error(y, model.predict(X))
#(gerçek değerler, tahmin edilen değerler)
MSE

import numpy as np
RMSE = np.sqrt(MSE)
RMSE

"""## **MODEL TUNİNG**(Model Doğrulaması)"""

X.head() #bağımsız değişkenler

y.head() #bağımlı değişkenler

#Sınama Seti
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test =train_test_split(X, y, test_size = 0.20, random_state = 99 )

"""Kodu her çalıştırdığımızda farklı sonuçlar gelmemesi için:
> random_state =  99
"""

X_train, X_test, y_train, y_test =train_test_split(X, y, test_size = 0.20, random_state = 99 )

X_train.head() #Train setinin bağımısz değişkenleri

y_train.head() #Train setinin bağımlı değişkenleri

X_test.head() #Test setinin bağımsız değişkenleri

y_test.head()

lm = LinearRegression()
model = lm.fit(X_train, y_train)

#Eğitim hatası
np.sqrt(mean_squared_error(y_train, model.predict(X_train)))

#Test hatası
np.sqrt(mean_squared_error(y_test, model.predict(X_test)))

# k katlı cv
from sklearn.model_selection import cross_val_score

#CV MSE
np.mean(-cross_val_score(model, X_train, y_train , cv=10, scoring ="neg_mean_squared_error"))

# CV RMSE
np.sqrt(np.mean(-cross_val_score(model, X_train, y_train , cv=10, scoring ="neg_mean_squared_error")))

"""Cross validation yöntemi doğrulanmış bir hata verir."""